version: '3.8'

services:
  app: &app_base
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ".:/rails"
    environment:
      RAILS_ENV: "development"
    command: bin/rails server -b '0.0.0.0'
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true

  tailwind:
    <<: *app_base
    ports: []
    command: bin/rails tailwindcss:watch
    depends_on:
      - app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geocodingapp_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
